import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

const __dirname = dirname(fileURLToPath(import.meta.url));

// eslint-config-next@15 ships legacy (eslintrc) configs, so they have to be
// bridged into flat config. Next 16 exports flat configs directly — if this
// project is ever upgraded, replace this with the direct imports.
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "src/lib/icons.ts", // generated
      "src/types/database.types.ts", // generated by `npm run db:types`
      "design/**", // the Stitch design package, kept verbatim for reference
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Server Actions and repositories legitimately return `any` from the
      // Supabase client in a few spots; surface them rather than silently pass.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
];

export default eslintConfig;
